-- MySQL Script generated by MySQL Workbench
-- 09/20/16 09:37:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema triggerdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema triggerdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `triggerdb` DEFAULT CHARACTER SET latin1 ;
USE `triggerdb` ;

-- -----------------------------------------------------
-- Table `triggerdb`.`schulklasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `triggerdb`.`schulklasse` (
  `idKlasse` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `groesse` INT(11) NOT NULL,
  `typ` VARCHAR(20) NOT NULL,
  `klassenName` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idKlasse`),
  UNIQUE INDEX `idKlasse` (`idKlasse` ASC),
  UNIQUE INDEX `idKlasse_2` (`idKlasse` ASC, `groesse` ASC),
  UNIQUE INDEX `idKlasse_3` (`idKlasse` ASC, `groesse` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

USE `triggerdb`;

DELIMITER $$
USE `triggerdb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `triggerdb`.`schulklasse_BEFORE_INSERT`
BEFORE INSERT ON `triggerdb`.`schulklasse`
FOR EACH ROW
BEGIN
IF NEW.groesse < 15 OR NEW.groesse > 30 THEN
SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'check constraint on Schulklasse.groesse failed';
END IF;

IF new.typ != 'IN' and new.typ != 'IMS' and new.typ != 'BL' and new.typ != 'BM' and new.typ != 'BS' THEN
SIGNAL SQLSTATE '12345' SET MESSAGE_TEXT = 'check constraint on Schulklasse.typ failed';
END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
